# Makefile automatically generated by ghdl
# Version: GHDL 4.1.0 (tarball) [Dunoon edition] - llvm 19.1.3 code generator
# Command used to generate this makefile:
# C:\msys64\mingw64\bin\ghdl.exe --gen-makefile --ieee=synopsys --workdir=WORK testbench

GHDL=C:\msys64\mingw64\bin\ghdl.exe
GHDLFLAGS= --ieee=synopsys --workdir=WORK

# Default target
all: testbench

# Elaboration target
testbench: C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164-body.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std-body.o WORK\testbench_AOC2_SoC.o WORK\AOC2_SoC.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o WORK\IO_MD_subsystem.o WORK\INCOMPLETE_Mips_segmentado_IRQ.o WORK\RAM_128_32_P1_2025.o WORK\REGISTER.o WORK\adder32.o WORK\RAM_I_test_exceptions.o WORK\Banco_ID.o WORK\BReg.o WORK\Ext_signo.o WORK\bits_shifter.o WORK\INCOMPLETE_UC_Mips_2025.o WORK\INCOMPLETE_UD_2025.o WORK\Banco_EX.o WORK\INCOMPLETE_UA_2025.o WORK\mux4_1.o WORK\mux2_1.o WORK\ALU.o WORK\mux2_5bits.o WORK\Banco_MEM.o WORK\Exception_manager.o WORK\Banco_WB.o WORK\counter.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: testbench
	$(GHDL) -r testbench $(GHDLRUNFLAGS)

# Targets to analyze files
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164-body.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/ieee/v93/numeric_std.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std-body.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/ieee/v93/numeric_std-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK\testbench_AOC2_SoC.o: testbench_AOC2_SoC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\AOC2_SoC.o: AOC2_SoC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/synopsys/std_logic_arith.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o: C:\msys64\mingw64\lib/ghdl\ieee\v93\../../src/synopsys/std_logic_unsigned.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK\IO_MD_subsystem.o: IO_MD_subsystem.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\INCOMPLETE_Mips_segmentado_IRQ.o: INCOMPLETE_Mips_segmentado_IRQ.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\RAM_128_32_P1_2025.o: RAM_128_32_P1_2025.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\REGISTER.o: REGISTER.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\adder32.o: adder32.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\RAM_I_test_exceptions.o: RAM_I_test_exceptions.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Banco_ID.o: Banco_ID.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\BReg.o: BReg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Ext_signo.o: Ext_signo.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\bits_shifter.o: bits_shifter.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\INCOMPLETE_UC_Mips_2025.o: INCOMPLETE_UC_Mips_2025.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\INCOMPLETE_UD_2025.o: INCOMPLETE_UD_2025.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Banco_EX.o: Banco_EX.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\INCOMPLETE_UA_2025.o: INCOMPLETE_UA_2025.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\mux4_1.o: mux4_1.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\mux2_1.o: mux2_1.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\ALU.o: ALU.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\mux2_5bits.o: mux2_5bits.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Banco_MEM.o: Banco_MEM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Exception_manager.o: Exception_manager.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\Banco_WB.o: Banco_WB.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK\counter.o: counter.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o: 
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164-body.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std-body.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\testbench_AOC2_SoC.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\AOC2_SoC.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o
WORK\IO_MD_subsystem.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o
WORK\INCOMPLETE_Mips_segmentado_IRQ.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\RAM_128_32_P1_2025.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\REGISTER.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\adder32.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\RAM_I_test_exceptions.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o
WORK\Banco_ID.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\BReg.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o
WORK\Ext_signo.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\bits_shifter.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\INCOMPLETE_UC_Mips_2025.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\INCOMPLETE_UD_2025.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\Banco_EX.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\INCOMPLETE_UA_2025.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\mux4_1.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\mux2_1.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\ALU.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
WORK\mux2_5bits.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\Banco_MEM.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\Exception_manager.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\Banco_WB.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o
WORK\counter.o:  C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_1164.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_arith.o C:\msys64\mingw64\lib/ghdl\ieee\v93\std_logic_unsigned.o C:\msys64\mingw64\lib/ghdl\ieee\v93\numeric_std.o
